language: java

jdk:
    - oraclejdk8

services:
    - mysql

before_install: 
    - mysql -uroot -e "grant all on admin.* to admin@localhost identified by 'java'"
    - mysql -uroot -e "drop database if exists dbtemplate"
    - mysql -uroot -e "create database dbtemplate"